
# Define a list of keywords related to trading
trading_keywords = ["get account details", "fetch my account details", "retrieve account information","place a trade", "execute a trade", "enter a trade","buy order", "whats your name", "Trading Pal", "price to earnings", "PEG ratio", 
"price to earnings growth", "placing a trade", "market cap", "capitalization", "market order", 
"short interest", "dividend yield", "ROE", "return on equity", "ROA", "return on assets", 
"ROI", "return on investment", "current ratio", "quick ratio", "debt to equity", 
"profit margin", "gross margin", "operating margin", "net margin", "cash flow", 
"free cash flow", "EBITDA", "earnings before interest, taxes, depreciation, and amortization", 
"amortization", "depreciation", "capital expenditure", "capex", "inventory", 
"accounts receivable", "accounts payable", "liquidity ratio", "coverage ratio", 
"turnover ratio", "efficiency ratio", "leverage ratio", "solvency ratio", 
"FAANG", "Facebook", "Apple", "Amazon", "Netflix", "Google", "Alphabet", 
"Tesla", "Microsoft", "Nvidia", "AMD", "Intel", "Qualcomm", "Cisco", "Oracle", 
"IBM", "S&P 500", "Dow Jones", "Nasdaq", "FTSE 100", "Nikkei 225", "Hang Seng", 
"DAX", "CAC 40", "ASX 200", "BSE Sensex", "Nifty 50", "MSCI", "Russell 2000", 
"Wilshire 5000", "VIX", "volatility index", "gold", "silver", "platinum", "palladium", 
"oil", "crude oil", "natural gas", "gasoline", "heating oil", "coal", "corn", 
"wheat", "soybeans", "cotton", "sugar", "coffee", "cocoa", "rice", "oats", "barley", 
"livestock", "cattle", "hogs", "pork bellies", "lumber", "copper", "aluminum", 
"nickel", "zinc", "lead", "tin", "iron ore", "steel", "uranium", "lithium", "cobalt", 
"rare earths", "potash", "fertilizers", "agriculture", "metals", "mining", 
"energy", "utilities", "technology", "healthcare", "pharmaceuticals", "biotech", 
"consumer goods", "consumer services", "retail", "wholesale", "e-commerce", 
"industrials", "manufacturing", "construction", "real estate", "transportation", 
"logistics", "telecom", "media", "entertainment", "education", "travel", 
"hospitality", "food and beverages", "banking", "insurance", "finance", 
"investment", "private equity", "venture capital", "hedge funds", "ETFs", 
"exchange-traded funds", "mutual funds", "index funds", "managed funds", "passive investing", 
"active investing", "robo-advisors", "financial planning", "retirement planning", 
"estate planning""trade", "account", "transaction", "buy", "sell", "units", "position", "open", 
"close", "EUR/USD", "USD/JPY", "GBP/USD", "AUD/USD", "USD/CAD", "USD/CHF", "NZD/USD", 
"bitcoin", "ethereum", "ripple", "litecoin", "stop loss", "take profit", "limit order", 
"market order", "leverage", "margin", "long", "short", "bid", "ask", "spread", 
"volume", "liquidity", "pips", "lot", "bullish", "bearish", "breakout", "pullback", 
"reversal", "consolidation", "divergence", "overbought", "oversold", "resistance", 
"support", "trendline", "channel", "range", "volatility", "indicator", "RSI", "MACD", 
"Bollinger Bands", "moving average", "Fibonacci", "Ichimoku Cloud", "Stochastic", 
"ADX", "ATR", "CCI", "Pivot Points", "Parabolic SAR", "broker", "platform", 
"chart", "candlestick", "bar chart", "line chart", "order book", "fundamental analysis", 
"technical analysis", "sentiment analysis", "quantitative analysis", "qualitative analysis", 
"day trading", "swing trading", "scalping", "position trading", "carry trade", "hedging", 
"arbitrage", "martingale", "grid trading", "cost averaging", "pairs trading", 
"momentum trading", "mean reversion", "trend following", "breakout trading", 
"news trading", "value investing", "growth investing", "income investing", 
"dollar cost averaging", "lump sum investing", "dividend reinvestment", "asset allocation", 
"diversification", "risk management", "money management", "risk/reward ratio", "drawdown", 
"equity curve", "ROI", "return on investment", "profit factor", "Sharpe ratio", 
"Sortino ratio", "beta", "alpha", "standard deviation", "variance", "volatility index", 
"VIX", "futures", "options", "CFDs", "ETFs", "mutual funds", "bonds", "commodities", 
"real estate", "REITs", "indices", "index funds", "stocks", "shares", "securities", 
"derivatives", "swaps", "forwards", "interest rate", "yield", "dividend", "IPO", 
"initial public offering", "private equity", "venture capital", "leverage buyout", 
"mergers and acquisitions", "M&A", "bankruptcy", "debt", "credit", "rating", 
"inflation", "deflation", "stagflation", "recession", "depression", "economic growth", 
"GDP","forex", "crypto", "stock", "market", "trading", "currency", "bitcoin", "equity", "shares",  "forex",
"currency", "exchange rate", "pip", "lot", "spread", "margin", "leverage", "technical analysis",
"fundamental analysis", "indicator", "trend", "chart", "candlestick", "support", "resistance",
"crypto", "cryptocurrency", "bitcoin", "ethereum", "altcoin", "wallet", "blockchain", "mining",
"trading", "stock", "equity", "share", "market", "stock exchange", "index", "commodity", "futures",
"options", "bond", "yield", "dividend", "earnings", "valuation", "portfolio", "risk management",
"order", "stop loss", "take profit", "trailing stop", "position sizing", "risk-reward ratio",
"position management", "scalping", "day trading", "swing trading", "position trading", "long",
"short", "buy", "sell", "bid", "ask", "liquidity", "volume", "price action", "moving average",
"momentum", "oscillator", "RSI", "MACD", "Bollinger Bands", "Fibonacci retracement", "Elliott wave",
"crossover", "divergence", "support and resistance levels", "whipsaw", "gap", "pullback", "breakout",
"reversal", "continuation", "trend line", "candlestick pattern", "doji", "hammer", "engulfing", "harami",
"morning star", "evening star", "bullish", "bearish", "uptrend", "downtrend", "sideways market",
"volatility", "correlation", "diversification", "risk appetite", "fundamental news", "economic calendar",
"central bank", "interest rate", "inflation", "unemployment", "GDP", "earnings report", "SEC filings",
"insider trading", "market sentiment", "technical analysis software", "fundamental analysis software",
"trading platform", "broker", "spread betting", "CFD", "liquidity provider", "market maker", "order book",
"depth chart", "trade history", "position book", "risk management tool", "backtesting", "EUR/USD",
"live trading", "place", "trade", "instrument", "units","place a trade", "execute a trade", "enter a trade", "initiate a trade", "start a trade",
"establish a trade", "set a trade", "arrange a trade", "implement a trade",
"proceed with a trade", "carry out a trade", "perform a trade", "organize a trade",
"launch a trade", "put in a trade", "begin a trade", "kick off a trade", "activate a trade",
"trigger a trade", "apply a trade", "commit to a trade", "finalize a trade", "authorize a trade",
"confirm a trade", "validate a trade", "get my account details", "fetch my account details", "retrieve account information",
"show me my account details", "can I see my account details", "display my account information",
"provide my account details", "pull up my account details", "bring up my account information",
"let me see my account details", "access my account details", "uncover my account details",
"reveal my account details", "dig up my account information", "find my account details",
"present my account information", "check my account details", "look up my account information",
"see my account details", "unveil my account details", "expose my account information",
"inspect my account details", "view my account information", "discover my account details",
"outline my account information"]
